version: '3.8'

services:
  webflux-db:
    image: postgres:13.1-alpine
    container_name: blog-db
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog
    restart: always